# Generated by Django 6.0.2 on 2026-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='driver_number',
            field=models.CharField(blank=True, default='16', max_length=4),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='nationality',
            field=models.CharField(blank=True, default='NL', max_length=40),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='team',
            field=models.CharField(default='Scuderia Ferrari', max_length=60),
        ),
    ]
