# Generated by Django 6.0.2 on 2026-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_pilotprofile_age_pilotprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='admin_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
