# Generated by Django 6.0.2 on 2026-02-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_checkin_admin_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('length_km', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('laps', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceWeekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2026)),
                ('round', models.PositiveIntegerField()),
                ('gp_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekends', to='tracking.circuit')),
            ],
            options={
                'ordering': ['season', 'round'],
                'unique_together': {('season', 'round')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gap_to_p1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wdc', to='tracking.raceweekend')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FP1', 'Free Practice 1'), ('FP2', 'Free Practice 2'), ('FP3', 'Free Practice 3'), ('Q', 'Qualifying'), ('R', 'Race')], max_length=3)),
                ('weekend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracking.raceweekend')),
            ],
            options={
                'unique_together': {('weekend', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('best_lap_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('laps', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Finished', max_length=50)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tracking.session')),
            ],
        ),
    ]
